services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
            - ./backend/.env
        ports:
            - '5000:5000'
        extra_hosts:
            - 'host.docker.internal:host-gateway'

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - '4000:4000'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
